---
title: "TugasAkhirDS"
author: "Alifia Rahma De Anissa"
date: "12/6/2021"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)
library(dslabs)
library(dplyr)
library(ggplot2)
library(shiny)
library(plotly)
library(tm)
library(glue)


datakomentar <- read.csv("Z:/Kuliah/Semester 5/Prak. Data Science/praktikum2020-Alifia/praktikum2020-master/123190034-123190044/sentiment_all.csv")
```


```{r}
corpuskomen <- Corpus(VectorSource(datakomentar$komentar))
komenbersih <- tm_map(corpuskomen, content_transformer(tolower))

```

```{r}

TextDoc_dtm <- TermDocumentMatrix(komenbersih)
dtm_m <- as.matrix(TextDoc_dtm)
dtm_v <- sort(rowSums(dtm_m),decreasing=TRUE)
dtm_d <- data.frame(word = names(dtm_v),freq=dtm_v)
```

```{r}
ui <- fluidPage(titlePanel("Visualisasi Data Berdasarkan Komentar Masyarakat Terhadap Penanganan Covid-19 di Indonesia"),
               sidebarLayout(
                 sidebarPanel(
                   actionButton("positif","Visualisasi komentar bernilai Positif"),
                   actionButton("neutral","Visualisasi komentar bernilai Netral"),
                   actionButton("negatif", "Visualisasi komentar bernilai Negatif"),
                   actionButton("top", "Visualisasi Kata yang sering muncul")
                 ),
                
                 mainPanel(
                   plotlyOutput(outputId = "aq_plot")
                 )
     )
)
```

```{r server}
server <- function(input, output, session) {
                 observeEvent( input$positif,{
                  result <- datakomentar %>%
                    group_by(Sentimen) %>% filter(Sentimen == "pos") %>%
                    summarise(jumlah = length(Sentimen)) %>%
                    ggplot(aes(x=Sentimen, y=jumlah)) + geom_col() + 
  labs(x = "Label Positif", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Positif", 
                                                                                        subtitle = "Visualisasi berdasarkan komentar bernilai positif")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$neutral,{
                   result <- datakomentar %>%
                    group_by(Sentimen) %>% filter(Sentimen == "neu") %>%
                    summarise(jumlah = length(Sentimen)) %>%
                    ggplot(aes(x=Sentimen, y=jumlah)) + geom_col() + 
  labs(x = "Label Netral", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Netral", 
                                                                                        subtitle = "Visualisasi berdasarkan komentar bernilai netral")
                   output$aq_plot<-renderPlotly(result)
                 })
                 observeEvent( input$negatif, { 
                   result <- datakomentar %>%
                     group_by(Sentimen) %>%
                    filter(Sentimen == "neg") %>% 
                    summarise(jumlah = length(Sentimen)) %>%
                    ggplot(aes(x=Sentimen, y=jumlah)) + geom_col() + 
labs(x = "Label Negatif", 
                                                                                        y = "Jumlah Review", 
                                                                                        title = "Grafik Label Negatif", 
                                                                                        subtitle = "Visualisasi berdasarkan komentar bernilai negatif")
                   output$aq_plot<-renderPlotly(result)
                 })
    
                 observeEvent( input$top,{
                  top = head(dtm_d)
                  result <- top %>% ggplot(aes(x=word, y=freq)) + geom_col() +coord_flip() + labs(x = "Kata",
                                                                                       y = "Frekuensi",
                                                                                       title = "Grafik kemunculan kata-kata",
                                                                                       subtitle = "Kata kata dengan kemunculan paling banyak")
                   output$aq_plot<-renderPlotly(result)
                 })
}
```

```{r run-app}
shinyApp(ui = ui, server = server, options = list(height = "700px"))
```
```
